import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "../components/sidebar";
import React from "react";
import Header from "@/components/header/Header";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased flex flex-row`}>
        <SideBar />
        <div className="flex flex-col w-full min-h-screen items-center max-w-8xl mx-auto px-12 py-14 gap-5">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
